# Generated by Django 5.2.11 on 2026-02-22 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('scope', models.TextField(help_text='Describe the scope and boundaries of this assessment.')),
                ('assessor_name', models.CharField(max_length=255)),
                ('assessor_email', models.EmailField(blank=True, max_length=254)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_auditee', models.ForeignKey(blank=True, help_text='Auditee organization being assessed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assessments', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Auditor responsible for this assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpactCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_area', models.CharField(choices=[('reputation', 'Reputation & Customer Confidence'), ('financial', 'Financial'), ('productivity', 'Productivity'), ('safety', 'Safety & Health'), ('legal', 'Fines & Legal Penalties'), ('custom', 'User-Defined / Other')], max_length=20)),
                ('area_label', models.CharField(blank=True, help_text='Custom label if "User-Defined", e.g. "Operational Continuity"', max_length=255)),
                ('criterion', models.CharField(help_text='Name of this sub-criterion, e.g. "Revenue Loss", "Customer Loss"', max_length=255)),
                ('low_criteria', models.TextField(help_text='Describe what constitutes a LOW impact for this criterion.')),
                ('mod_criteria', models.TextField(help_text='Describe what constitutes a MODERATE impact for this criterion.')),
                ('high_criteria', models.TextField(help_text='Describe what constitutes a HIGH impact for this criterion.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_criteria', to='octave_app.assessment')),
            ],
            options={
                'ordering': ['impact_area', 'criterion'],
            },
        ),
        migrations.CreateModel(
            name='InformationAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the information asset.', max_length=255)),
                ('description', models.TextField(help_text='Brief description of what this asset is.')),
                ('rationale', models.TextField(help_text='Why is this asset important? What would happen if it were lost or compromised?')),
                ('owner', models.CharField(help_text='Person or group responsible for this asset.', max_length=255)),
                ('owner_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=10)),
                ('req_confidentiality', models.TextField(help_text='Who should have access? What would disclosure cause?')),
                ('req_integrity', models.TextField(help_text='What accuracy/completeness requirements exist? Impact of modification?')),
                ('req_availability', models.TextField(help_text='How available must this asset be? Impact of downtime?')),
                ('most_important_req', models.CharField(choices=[('confidentiality', 'Confidentiality'), ('integrity', 'Integrity'), ('availability', 'Availability')], help_text='Which single CIA property is MOST critical for this asset?', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='octave_app.assessment')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type', models.CharField(choices=[('internal_technical', 'Internal Technical'), ('external_technical', 'External Technical'), ('physical', 'Physical'), ('people', 'People')], max_length=30)),
                ('name', models.CharField(help_text='Name of this container (e.g. "Email Server", "HR Department")', max_length=255)),
                ('description', models.TextField(help_text='Describe this container and how the asset is stored/transported/processed here.')),
                ('location', models.CharField(blank=True, help_text='Physical or network location of this container.', max_length=255)),
                ('owner', models.CharField(blank=True, help_text='Who owns or manages this container?', max_length=255)),
                ('is_critical', models.BooleanField(default=False, help_text='Is this a critical container for this asset?')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='octave_app.informationasset')),
            ],
            options={
                'ordering': ['container_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ThreatScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_concern', models.TextField(help_text='Describe the area of concern that prompted this threat scenario.')),
                ('scenario_name', models.CharField(help_text='Brief name for this threat scenario.', max_length=255)),
                ('actor', models.TextField(help_text='(1) Actor — Who would exploit this area of concern or threat? e.g. Hacker, Insider, Competitor, Natural disaster.')),
                ('means', models.TextField(help_text='(2) Means — How would the actor do it? What tools or methods would they use?')),
                ('motive', models.TextField(help_text="(3) Motive — What is the actor's reason for doing this?")),
                ('outcome', models.TextField(help_text='(4) Outcome — What would be the resulting effect on the information asset? (Disclosure, Modification, Destruction, Interruption)')),
                ('access_path', models.TextField(help_text='(5) Access Path — How would the actor gain access to the asset or its containers?')),
                ('probability', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='(6) Probability — How likely is this threat scenario to occur?', max_length=10)),
                ('consequences', models.TextField(help_text='(7) Consequences — What are the consequences to the organisation if this threat is realised? Consider the most important security requirement.')),
                ('impact_area', models.CharField(blank=True, choices=[('reputation', 'Reputation & Customer Confidence'), ('financial', 'Financial'), ('productivity', 'Productivity'), ('safety', 'Safety & Health'), ('legal', 'Fines & Legal Penalties'), ('custom', 'User-Defined / Other')], help_text='Which impact area is most affected by this threat?', max_length=20, null=True)),
                ('impact_value', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High')], help_text='Step 7 — Classify the impact: Low=1, Moderate=2, High=3.', null=True)),
                ('impact_rationale', models.TextField(blank=True, help_text='Briefly explain why you chose this impact level.')),
                ('mitigation_strategy', models.CharField(blank=True, choices=[('mitigate', 'Mitigate'), ('transfer', 'Transfer'), ('accept', 'Accept'), ('avoid', 'Avoid'), ('defer', 'Defer')], max_length=10, null=True)),
                ('mitigation_plan', models.TextField(blank=True, help_text='Describe what will be done to address this risk.')),
                ('mitigation_rationale', models.TextField(blank=True, help_text='Why was this mitigation strategy chosen?')),
                ('responsible_party', models.CharField(blank=True, max_length=255)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('mitigation_status', models.CharField(blank=True, choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threats', to='octave_app.informationasset')),
                ('container', models.ForeignKey(blank=True, help_text='Which container does this threat originate from or affect?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threats', to='octave_app.assetcontainer')),
            ],
            options={
                'ordering': ['asset', 'scenario_name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('auditor', 'Auditor'), ('auditee', 'Auditee')], default='auditee', max_length=10)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_area', models.CharField(choices=[('reputation', 'Reputation & Customer Confidence'), ('financial', 'Financial'), ('productivity', 'Productivity'), ('safety', 'Safety & Health'), ('legal', 'Fines & Legal Penalties'), ('custom', 'User-Defined / Other')], max_length=20)),
                ('area_label', models.CharField(blank=True, help_text='If custom area, enter its name here.', max_length=255)),
                ('priority_rank', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rank: 5 = most important, 1 = least important. Each rank must be unique.')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_priorities', to='octave_app.assessment')),
            ],
            options={
                'ordering': ['-priority_rank'],
                'unique_together': {('assessment', 'impact_area'), ('assessment', 'priority_rank')},
            },
        ),
    ]
